title: Custom Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
header_color: "#000"
gradient_color_left: "#e53935"
gradient_color_right: "#f57c00"